version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run semantic-release
workflows:
  build-and-test:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - '+([0-9])?(.{+([0-9]),x}).x'
                - 'stable'
                - 'rc'
                - 'beta'
                - 'alpha'
                - 'dev'
